Repository google/certificate-transparency-go, pull requests merged in 2019-07, with the labels that each got.

#557 Don't copy migrillian config protos by value in tests.
  trillian/migrillian/core/config_test.go
Labels: cla: yes

#556 Fix incorrect copying of config protos.
  trillian/ctfe/config_test.go
  trillian/ctfe/instance_test.go
  trillian/integration/ct_integration_test.go
Labels: cla: yes

#558 Fix incorrect proto copying for client multilog config.
  client/multilog.go
  client/multilog_test.go
  preload/preloader/preloader.go
Labels: cla: yes

#559 Bug-fix
  x509util/x509util.go
Labels: cla: yes

#560 Add simple /healthz handler in ctfe
  trillian/ctfe/ct_server/main.go
Labels: cla: yes

#563 Merging 2 identical Loglist-filter functions
  loglist2/logfilter.go
  loglist2/logfilter_test.go
Labels: cla: yes

#562 Convert some tests to use t.Run
  jsonclient/client_test.go
  trillian/ctfe/handlers_test.go
Labels: cla: yes

#561 Adding init-callback for proxy.
  submission/proxy.go
  submission/proxy_server.go
  submission/proxy_test.go
Labels: cla: yes

#564 Unifying root/temporal/status Log-filtering under Compatible call
  loglist2/logfilter.go
  loglist2/logfilter_test.go
  loglist2/loglist2_test.go
Labels: cla: yes

#567 Cleanup dns client tests.
  dnsclient/dnsclient_test.go
Labels: cla: yes

#570 Fixing some unhappiness
  .travis.yml
  go.mod
  go.sum
Labels: cla: yes

#565 Fix var / package collisions and extra parens
  client/ctclient/ctclient.go
  ctpolicy/ctpolicy.go
  ctpolicy/ctpolicy_test.go
  ctpolicy/tools_test.go
  ctutil/ctutil_test.go
  ctutil/sctcheck/sctcheck.go
  fixchain/fixer.go
  fixchain/hash.go
  gossip/handler.go
  gossip/handler_test.go
  gossip/minimal/goshawk_test.go
  ingestor/ranges/tracker_test.go
  logid/logid_test.go
  loglist2/loglist2_test.go
  preload/preloader/preloader.go
  scanner/scanlog/scanlog.go
  serialization_test.go
  submission/distributor.go
  submission/distributor_test.go
  submission/loglist_manager.go
  trillian/ctfe/handlers.go
  trillian/ctfe/pem_cert_pool_test.go
  trillian/integration/logenv.go
  trillian/util/resolver_test.go
  types_test.go
  x509/error.go
  x509/names.go
  x509/names_test.go
  x509/pkcs8_test.go
  x509/revoked_test.go
  x509/rpki_test.go
  x509/verify.go
  x509/x509.go
  x509/x509_test.go
Labels: cla: yes

#572 Fix up partially reverted change.
  trillian/ctfe/handlers.go
Labels: cla: yes

#568 Extending tests for Proxy init-status
  submission/loglist_manager.go
  submission/proxy_test.go
Labels: cla: yes

#571 [ctfe] Reject submissions based on extensions present
  CHANGELOG.md
  trillian/ctfe/cert_checker.go
  trillian/ctfe/cert_checker_test.go
  trillian/ctfe/configpb/config.pb.go
  trillian/ctfe/configpb/config.proto
  trillian/ctfe/configpb/gen.go
  trillian/ctfe/handlers.go
  trillian/ctfe/instance.go
  trillian/ctfe/instance_test.go
Labels: cla: yes, feature

#573 Prefix port name with "http-" in ctfe-deployment.yaml
  trillian/examples/deployment/kubernetes/ctfe-deployment.yaml
Labels: cla: yes, enhancement

#576 Add more missing CHANGELOG entries
  CHANGELOG.md
Labels: cla: yes

#577 Do not send Log-list updates when no update passed.
  submission/loglist_manager.go
  submission/loglist_manager_test.go
Labels: cla: yes

#579 Add metrics onto proxy level. Add counter for Loglist updates
  submission/distributor.go
  submission/proxy.go
  submission/proxy_server.go
  submission/proxy_test.go
  submission/server/main.go
Labels: cla: yes

#581 Add even more missing CHANGELOG entries
  CHANGELOG.md
Labels: cla: yes

#583 Partially Revert "Fix var / package collisions and extra parens"
  x509/error.go
  x509/names.go
  x509/names_test.go
  x509/pkcs8_test.go
  x509/revoked_test.go
  x509/rpki_test.go
  x509/verify.go
  x509/x509.go
  x509/x509_test.go
Labels: cla: yes

#566 Some cleanup for ctutil.
  ctutil/ctutil_test.go
  ctutil/sctcheck/sctcheck.go
  ctutil/sctscan/sctscan.go
Labels: cla: yes

#585 Allow tuning of dupe adds in Hammer
  CHANGELOG.md
  trillian/integration/ct_hammer/main.go
  trillian/integration/hammer.go
  trillian/integration/hammer_test.go
Labels: cla: yes, enhancement

#584 Add notices to x509 and asn1 packages that they are forks.
  asn1/README.md
  x509/README.md
Labels: cla: yes

#580 Copy-paste preparing switch from loglist to loglist2
  ctpolicy/applepolicy.go
  ctpolicy/applepolicy_test.go
  ctpolicy/chromepolicy.go
  ctpolicy/chromepolicy_test.go
  ctpolicy/ctpolicy.go
  ctpolicy/ctpolicy_test.go
  loglist2/loglist2.go
  loglist2/loglist2_test.go
  submission/distributor_test.go
  testdata/loglist2.go
Labels: cla: yes

#587 Fix incomplete error handing in races test.
  submission/races_test.go
Labels: cla: yes

#588 LogsByGroup doesn't return any data when error produced
  ctpolicy/applepolicy.go
  ctpolicy/chromepolicy.go
  ctpolicy/chromepolicy_test.go
  ctpolicy/ctpolicy.go
Labels: cla: yes

#591 Closing Init channel on context timeout
  submission/proxy.go
Labels: cla: yes

#590 LoglistV1 -> LoglistV2 transition for proxy
  ctpolicy/applepolicy.go
  ctpolicy/applepolicy_test.go
  ctpolicy/chromepolicy.go
  ctpolicy/chromepolicy_test.go
  ctpolicy/ctpolicy.go
  ctpolicy/ctpolicy_test.go
  submission/distributor.go
  submission/distributor_test.go
  submission/loglist_refresher.go
  submission/loglist_refresher_test.go
  submission/proxy.go
  submission/proxy_test.go
  submission/stub.go
  testdata/loglist2.go
Labels: cla: yes

#594 Binary logic is difficult. Avoid closing channel twice
  submission/proxy.go
Labels: cla: yes

#593 Clean-up.
  asn1/README.md
  submission/distributor.go
  x509/README.md
Labels: cla: yes
