Repository google/certificate-transparency-go, pull requests merged in 2020-07, with the labels that each got.

#713 Allow checking of EKU on submissions
  CHANGELOG.md
  trillian/ctfe/cert_checker.go
  trillian/ctfe/cert_checker_test.go
  trillian/ctfe/config.go
  trillian/ctfe/config_test.go
  trillian/ctfe/handlers_test.go
  trillian/ctfe/testonly/certificates.go
Labels: cla: yes, enhancement

#665 Fork updates from Go 1.14
  CHANGELOG.md
  asn1/asn1.go
  asn1/asn1_test.go
  asn1/common.go
  x509/name_constraints_test.go
  x509/pkcs8.go
  x509/root_cgo_darwin.go
  x509/root_nacl.go
  x509/root_unix.go
  x509/root_windows.go
  x509/sec1.go
  x509/verify.go
  x509/x509.go
  x509/x509_test.go
Labels: cla: yes

#650 Correct flag name in CHANGELOG
  CHANGELOG.md
Labels: cla: yes, cleanup

#717 Fix spelling
  CHANGELOG.md
  ctpolicy/ctpolicy.go
  jsonclient/client.go
Labels: cla: yes

#716 Delete all gossip related code except for the x509ext package.
  CHANGELOG.md
  go.mod
  go.sum
  gossip/README.md
  gossip/examples/deployment/docker/gosmin/Dockerfile
  gossip/gossip_server/gossip_server.go
  gossip/handler.go
  gossip/handler_test.go
  gossip/minimal/README.md
  gossip/minimal/configpb/config.pb.go
  gossip/minimal/configpb/config.proto
  gossip/minimal/configpb/gen.go
  gossip/minimal/goshawk.go
  gossip/minimal/goshawk/main.go
  gossip/minimal/goshawk_test.go
  gossip/minimal/gosmin/main.go
  gossip/minimal/gossip.go
  gossip/minimal/gossip_test.go
  gossip/minimal/instance.go
  gossip/minimal/instance_test.go
  gossip/minimal/mysql/hawkstate.go
  gossip/minimal/mysql/state.sql
  gossip/minimal/serialization.go
  gossip/minimal/serialization_test.go
  gossip/minimal/testdata/Makefile
  gossip/minimal/testdata/ct-test.cfg
  gossip/minimal/testdata/ct-test.pb
  gossip/minimal/testdata/dup-source-name.cfg
  gossip/minimal/testdata/goshawk.cfg
  gossip/minimal/testdata/goshawk.pb
  gossip/minimal/testdata/gossiper.privkey.pem
  gossip/minimal/testdata/hawk-dup-source-name.cfg
  gossip/minimal/testdata/hawk-no-dest-name.cfg
  gossip/minimal/testdata/hawk-no-source-log.cfg
  gossip/minimal/testdata/hawk-no-source-name.cfg
  gossip/minimal/testdata/hub-test.cfg
  gossip/minimal/testdata/hub-test.pb
  gossip/minimal/testdata/invalid-private-key.cfg
  gossip/minimal/testdata/invalid-root-cert.cfg
  gossip/minimal/testdata/invalid-source-duration.cfg
  gossip/minimal/testdata/invalid-source-pubkey.cfg
  gossip/minimal/testdata/no-dest-hub.cfg
  gossip/minimal/testdata/no-dest-name.cfg
  gossip/minimal/testdata/no-private-key.cfg
  gossip/minimal/testdata/no-root-cert.cfg
  gossip/minimal/testdata/no-source-log.cfg
  gossip/minimal/testdata/no-source-name.cfg
  gossip/minimal/testdata/root-ca.cert
  gossip/minimal/testdata/root-ca.cfg
  gossip/minimal/testdata/wrong-password-private-key.cfg
  gossip/storage.go
  gossip/types.go
  scripts/resetctdb.sh
  trillian/integration/ct_functions.sh
  trillian/integration/ct_hammer_test.sh
  trillian/integration/ct_killall.sh
Labels: cla: yes

#719 Travis: go mod tidy allowed to fail
  .travis.yml
Labels: cla: yes

#721 Switch CTFE main to go.etcd.io version. Bump trillian to 1.3.10.
  .travis.yml
  CHANGELOG.md
  client/configpb/gen.go
  client/configpb/multilog.pb.go
  client/configpb/multilog.proto
  client/multilog.go
  go.mod
  go.sum
  tools.go
  trillian/ctfe/config.go
  trillian/ctfe/config_test.go
  trillian/ctfe/configpb/config.pb.go
  trillian/ctfe/ct_server/main.go
  trillian/ctfe/handlers.go
  trillian/ctfe/handlers_test.go
  trillian/ctfe/sth.go
  trillian/integration/ct_functions.sh
  trillian/migrillian/configpb/config.pb.go
  trillian/migrillian/core/config.go
Labels: cla: yes

#722 Use go 1.14 for Travis, the same as the trillian repo.
  .travis.yml
  go.mod
Labels: cla: yes
